export const ASTNodeKind = Object.freeze({
  // declarations
  FUNCTION_DECL: "FUNCTION_DECL",
  LET_DECL: "LET_DECL",
  CONST_DECL: "CONST_DECL",
  TYPE_DECL: "TYPE_DECL",
  FIELD_DECL: "FIELD_DECL",
  DESTRUCTURE_DECL: "DESTRUCTURE_DECL",
  IMPORT_DECL: "IMPORT_DECL",
  EXPORT_DECL: "EXPORT_DECL",
  EXTERN_FUNCTION_DECL: "EXTERN_FUNCTION_DECL",
  EXTERN_TYPE_DECL: "EXTERN_TYPE_DECL",
  EXPORT_C_FUNCTION_DECL: "EXPORT_C_FUNCTION_DECL",

  // literals
  TEMPLATE_LITERAL: "TEMPLATE_LITERAL",
  STRING_PART: "STRING_PART",
  INT_LITERAL: "INT_LITERAL",
  FLOAT_LITERAL: "FLOAT_LITERAL",
  STRING_LITERAL: "STRING_LITERAL",
  BOOL_LITERAL: "BOOL_LITERAL",

  // expressions
  CALL_EXPRESSION: "CALL_EXPRESSION",
  EXPRESSION_STATEMENT: "EXPRESSION_STATEMENT",
  EXPR_PART: "EXPR_PART",
  UNARY_EXPRESSION: "UNARY_EXPRESSION",
  BINARY_EXPRESSION: "BINARY_EXPRESSION",
  FIELD_ACCESS: "FIELD_ACCESS",
  STRUCT_LITERAL: "STRUCT_LITERAL",
  STRUCT_LITERAL_FIELD: "STRUCT_LITERAL_FIELD",

  // other
  EXTERN_BLOCK: "EXTERN_BLOCK",
  BLOCK: "BLOCK",
  PARAM: "PARAM",
  IDENT: "IDENT",
  NAMESPACE_IDENT: "NAMESPACE_IDENT",
  ASSIGNMENT: "ASSIGNMENT",
  PROGRAM: "PROGRAM",
  RETURN_STATEMENT: "RETURN_STATEMENT",
  IF_STATEMENT: "IF_STATEMENT",
  WHILE_STATEMENT: "WHILE_STATEMENT",
  DISCARD_STATEMENT: "DISCARD_STATEMENT",
  TRY_OP: "TRY_OP",

  // phase 4: refs, arrays, control flow
  FOR_LOOP: "FOR_LOOP",
  BREAK_STATEMENT: "BREAK_STATEMENT",
  CONTINUE_STATEMENT: "CONTINUE_STATEMENT",
  ARRAY_LITERAL: "ARRAY_LITERAL",
  INDEX_EXPRESSION: "INDEX_EXPRESSION",
  REF_EXPRESSION: "REF_EXPRESSION",

  // phase 5: traits
  TRAIT_DECL: "TRAIT_DECL",
  METHOD_SIG: "METHOD_SIG",
  METHOD_DECL: "METHOD_DECL",

  // phase 6: kinds
  KIND_DECL: "KIND_DECL",
  KIND_APPLIES_TO_CLAUSE: "KIND_APPLIES_TO_CLAUSE",
  KIND_REQUIRES_CLAUSE: "KIND_REQUIRES_CLAUSE",
  KIND_MUSTCALL_CLAUSE: "KIND_MUSTCALL_CLAUSE",
  KIND_OWNSBLOCK_CLAUSE: "KIND_OWNSBLOCK_CLAUSE",
  CLEANUP_CALL: "CLEANUP_CALL",
  // phase 6.2: escape and sharing
  KIND_MUST_NOT_ESCAPE_CLAUSE: "KIND_MUST_NOT_ESCAPE_CLAUSE",
  KIND_MUST_NOT_SHARE_CLAUSE: "KIND_MUST_NOT_SHARE_CLAUSE",
  KIND_FORBIDS_CLAUSE: "KIND_FORBIDS_CLAUSE",

  // test undefined kind handling for iteration tests
  FAIL_TEST_KIND: "FAIL_TEST_KIND",
});

export function SourceLocation(pos, line, column) {
  this.pos = pos;
  this.line = line;
  this.column = column;
}

export function ASTNode(kind, sourceLoc) {
  this.kind = ASTNodeKind[kind];
  if (!this.kind) {
    throw new Error(`Invalid AST node kind: ${kind}`);
  }
  if (sourceLoc) {
    this.sourceLoc = new SourceLocation(sourceLoc.pos, sourceLoc.line, sourceLoc.column);
  }
}
