export const ASTNodeKind = Object.freeze({
  // declarations
  FUNCTION_DECL: "FUNCTION_DECL",
  LET_DECL: "LET_DECL",
  CONST_DECL: "CONST_DECL",

  // literals
  TEMPLATE_LITERAL: "TEMPLATE_LITERAL",
  STRING_PART: "STRING_PART",
  INT_LITERAL: "INT_LITERAL",
  FLOAT_LITERAL: "FLOAT_LITERAL",
  STRING_LITERAL: "STRING_LITERAL",

  // expressions
  CALL_EXPRESSION: "CALL_EXPRESSION",
  EXPRESSION_STATEMENT: "EXPRESSION_STATEMENT",
  EXPR_PART: "EXPR_PART",
  UNARY_EXPRESSION: "UNARY_EXPRESSION",
  BINARY_EXPRESSION: "BINARY_EXPRESSION",

  // other
  BLOCK: "BLOCK",
  PARAM: "PARAM",
  IDENT: "IDENT",
  ASSIGNMENT: "ASSIGNMENT",
  PROGRAM: "PROGRAM",
  RETURN_STATEMENT: "RETURN_STATEMENT",
  IF_STATEMENT: "IF_STATEMENT",
  WHILE_STATEMENT: "WHILE_STATEMENT",
});

export function ASTNode(kind) {
  this.kind = ASTNodeKind[kind];
}
