// Drift guard for std/INDEX.md.
//
// The index is GENERATED (tools/stdindex/main.yoop, `npm run gen:index`) and
// checked in, which is the arrangement that rots: someone adds a module, the
// index does not mention it, and a reader concludes the library does not have
// the thing. That failure is exactly what the index exists to prevent - a
// 15,000 line project hand-rolled digit loops in four files because it never
// found std/core/format.yoop (plans/yooperdoom-takeaways.md 4.1).
//
// This does NOT re-run the generator: that needs clang, and a check that only
// runs in the e2e suite is a check that runs less often than the mistake. It
// asserts COVERAGE instead - every importable module on disk has a heading,
// and every heading corresponds to something on disk - which is the drift that
// actually happens. Wording and export lists are the generator's business.

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const stdRoot = path.join(repoRoot, "std");
const indexPath = path.join(repoRoot, "std/INDEX.md");

// A source file opens a DIRECTORY module when its first non-comment line is
// `module <name>;`. Mirrors tools/stdindex and the parser's own rule.
function declaresModule(src) {
  for (const raw of src.split("\n")) {
    const line = raw.trim();
    if (line === "" || line.startsWith("//")) continue;
    return /^module\s+[A-Za-z_][A-Za-z0-9_]*\s*;$/.test(line);
  }
  return false;
}

function isDirectoryModule(dir) {
  const yoops = fs.readdirSync(dir).filter((n) => n.endsWith(".yoop"));
  if (yoops.length === 0) return false;
  return yoops.every((n) => declaresModule(fs.readFileSync(path.join(dir, n), "utf8")));
}

// Every import path a user can write for something under std/.
function collectModules(dir, importBase, out = []) {
  for (const name of fs.readdirSync(dir).sort()) {
    const full = path.join(dir, name);
    if (fs.statSync(full).isDirectory()) {
      const sub = `${importBase}/${name}`;
      if (isDirectoryModule(full)) out.push(sub);
      else collectModules(full, sub, out);
      continue;
    }
    if (!name.endsWith(".yoop")) continue;
    out.push(`${importBase}/${name}`);
  }
  return out;
}

describe("std/INDEX.md", () => {
  it("exists and says it is generated", () => {
    assert.ok(fs.existsSync(indexPath), "run `npm run gen:index`");
    const text = fs.readFileSync(indexPath, "utf8");
    assert.match(text, /Generated by `tools\/stdindex`/);
  });

  it("has a section for every importable module under std/", () => {
    const text = fs.readFileSync(indexPath, "utf8");
    const headings = new Set(
      [...text.matchAll(/^## `([^`]+)`$/gm)].map((m) => m[1]),
    );
    const onDisk = collectModules(stdRoot, "std");

    const missing = onDisk.filter((m) => !headings.has(m));
    assert.deepEqual(
      missing,
      [],
      `std/INDEX.md is stale - run \`npm run gen:index\`. Missing: ${missing.join(", ")}`,
    );
  });

  it("has nothing in it that is no longer on disk", () => {
    const text = fs.readFileSync(indexPath, "utf8");
    const headings = [...text.matchAll(/^## `([^`]+)`$/gm)].map((m) => m[1]);
    const onDisk = new Set(collectModules(stdRoot, "std"));

    const stale = headings.filter((h) => !onDisk.has(h));
    assert.deepEqual(
      stale,
      [],
      `std/INDEX.md lists modules that no longer exist - run \`npm run gen:index\`. Stale: ${stale.join(", ")}`,
    );
  });

  it("gives every module a non-empty summary", () => {
    // A module whose header the generator could not read shows up as a
    // heading with nothing under it, which is worse than an omission because
    // it looks intentional.
    const text = fs.readFileSync(indexPath, "utf8");
    const sections = text.split(/^## /m).slice(1);
    const empty = [];
    for (const section of sections) {
      const [heading, ...rest] = section.split("\n");
      const body = rest.join("\n").trim();
      if (body === "" || body.startsWith("Exports:") || body.startsWith("Source files")) {
        empty.push(heading.replace(/`/g, ""));
      }
    }
    assert.deepEqual(empty, [], `modules with no summary: ${empty.join(", ")}`);
  });
});
